language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - TERM=dumb
  - gradle -v
  - gradle check jacocoTestReport
after_success:
  - gradle jacocoRootReport coveralls
notifications:
  email: false
